In [1]:
print("Jupyter is working!")

Jupyter is working!


# My First Jupyter Notebook
This notebook is for practicing Python.

**Currently learning: NumPy basics**

In [19]:
u=np.array([[1,2,3],[2,3,4]])
v=np.array([[4,5,6],[5,7,8]])
print(np.concatenate((u,v)))

[[1 2 3]
 [2 3 4]
 [4 5 6]
 [5 7 8]]


In [18]:
u=np.array([1,2,3])
v=np.array([4,5,6])
print(np.concatenate((u,v)))

[1 2 3 4 5 6]


In [12]:
import numpy as np
u=np.array([[1,2,3],[2,3,4]])
v=np.array([[4,5,6],[5,7,8]])
s = np.stack([u,v])
print(s)

[[[1 2 3]
  [2 3 4]]

 [[4 5 6]
  [5 7 8]]]


In [ ]:
#hstack()-- horizontal stack
#vstack ()-- vertical stack

In [13]:
a = np.array([1,2,3,4])
b = np.array([2,4,5,6])
c = np.hstack([a,b])
print (c)
d = np.vstack([a,b])
print(d)

[1 2 3 4 2 4 5 6]
[[1 2 3 4]
 [2 4 5 6]]


**split function**

In [14]:
x=np.array([1,2,3,4,5,6])
y=np.array_split(x,2)
print(y)

[array([1, 2, 3]), array([4, 5, 6])]


In [15]:
z=np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
a=np.array_split(z,6)
print(a)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[6, 7, 8]]), array([[ 9, 10, 11]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]


In [16]:
#hsplit
b=np.hsplit(z,3)
print(b)

[array([[1],
       [4],
       [6],
       [9]]), array([[ 2],
       [ 5],
       [ 7],
       [10]]), array([[ 3],
       [ 6],
       [ 8],
       [11]])]


In [17]:
# vsplit
c=np.vsplit(z,2)
print(c)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 6,  7,  8],
       [ 9, 10, 11]])]


In [20]:
a=[3,1,2,3,4,5]
a.sort(reverse=True)
print(a)

[5, 4, 3, 3, 2, 1]


In [21]:
a=np.array([3,5,6,8,2,1])
print(np.sort(a))

[1 2 3 5 6 8]


In [22]:
a=np.array([3,5,6,8,2,1])
b=np.argsort(a)[::-1]
c=a[b]
print(c)

[8 6 5 3 2 1]


In [23]:
# # filter method
c=np.array([1,3,4,5,6])
b=[True,False,True,True,False]
print(c[b])

[1 4 5]


In [25]:
c=np.array([1,3,4,5,6])
d=c > 4
print(c[d])


[5 6]


In [27]:
# array initialization method
# 1. zeros() method
# 2. ones() method
# 3. full() method
# 4. arange() method
# 5. linspace() method
# 6.eye() method

In [28]:
a=np.zeros((2,3))
print(a)

a=np.ones((2,3))
print(a)

a=np.full((2,3),5)
print(a)

a=np.arange(1,10,2)
print(a)

c=np.linspace(0,20,num=15)
print(c)

d=np.eye(3)
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]]
[1 3 5 7 9]
[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.         11.42857143 12.85714286 14.28571429 15.71428571
 17.14285714 18.57142857 20.        ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:

a=np.array([[1,2,3,4],[5,6,7,8]])
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a+a)
print(a+2)
print(a*a)
print(a.sum())
print(a.min())
print(a.max())

[[ 2  4  6  8]
 [10 12 14 16]]
[[ 3  4  5  6]
 [ 7  8  9 10]]
[[ 1  4  9 16]
 [25 36 49 64]]
36
1
8
